pipeline:
  build:
    image: node:8
    commands:
      - npm install
      - npm run test
      - npm run lint
  slack:
    when:
      event: [ push ]
    image: plugins/slack
    username: drone
    channel: hourly-cli
    secrets: [ slack_webhook ]
    when: 
      status: [ success, failure ]
    template: >
      {{#success build.status}}
        build {{build.number}} succeeded.
      {{else}}
        build {{build.number}} failed.
      {{/success}}
  npm:
    image: plugins/npm
    secrets: [ npm_token ]
    email: jacob@johnstonjacob.com
    when:
      branch: master
branches:
  include: [ master, dev, feature/* ]
